config/routes.rb
Rails.application.routes.draw do
  resources :bmesseages
  resources :lessons
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  post 'join/:id', to: "lessons#join", as: "join_lesson"

  post 'comment/', to: "lessons#comment", as: "join_comment"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "lessons#index"
end

app/models/lesson.rb
class Lesson < ApplicationRecord
    validates :topic, presence: true
    validates :field, presence: true
    validates :description, presence: true
    belongs_to :user
    has_many :messages
    def user_email
        user.email
    end

      has_many :joinable, dependent: :destroy
      has_many :joins, through: :joinable, source: :user

   
  
    after_create_commit :broadcast_new_lesson
    after_update_commit :broadcast_updated_lesson
      
      
    after_destroy_commit do
      broadcast_destroy_lesson
    end
    
    def broadcast_new_lesson
      current_user = user
        broadcast_prepend_later_to 'public_lessons',
                                    target: 'public_lessons',
                                    partial: 'lessons/lesson',
                                    locals: { lesson: self, join_status: false,current_user: current_user }
        broadcast_prepend_later_to 'private_lessons',
                                    target: 'private_lessons',
                                    partial: 'lessons/lesson',
                                    locals: { lesson: self, join_status: false,current_user: current_user }
      end
    
      def broadcast_updated_lesson
        current_user = user
        shared_target_lesson = "lesson_#{id}"
        private_target_channel = "#{@user_gid} private_joins"
        broadcast_replace_later_to 'public_lessons',
                                    target: shared_target_lesson,
                                    partial: 'lessons/lesson',
                                    locals: { lesson: self,join_status: false, current_user: current_user }
        broadcast_replace_later_to "private_lessons",
                                    target: shared_target_lesson,
                                    partial: 'lessons/lesson',
                                    locals: { lesson: self, join_status: false, current_user: current_user }
      end

    
      def broadcast_destroy_lesson
        
        broadcast_remove_to 'public_lessons',
                            target: "lesson_#{id}"
        broadcast_remove_to 'private_lessons',
                            target: "lesson_#{id}"
      end
    
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /lessons or /lessons.json
  def index
    @lessons = Lesson.order(created_at: :desc)
    @user_gid=current_user.to_gid_param if current_user 
    #.limit(2)
  end
  # GET /lessons/1 or /lessons/1.json
  def show
    @bmesseage = Bmesseage.all
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
   
  end

  # POST /lessons or /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
          format.turbo_stream { render turbo_stream: turbo_stream.prepend( "private_lessons" , partial: "lessons/lesson", locals: {
            lesson: @lesson, join_status: current_user.joined?(@lesson) 
            })}
        format.turbo_stream do
          render turbo_stream: turbo_stream.prepend("lessons", partial: "lessons/lesson", locals: {lesson: @lesson, join_status: current_user.joined?(@lesson) })
        end
        format.html { redirect_to lesson_url(@lesson), notice: "Lesson was successfully created." }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1 or /lessons/1.json
  def update 
    if @lesson.user_id != current_user.id
       correct_user
      else
    respond_to do |format|
     
      if @lesson.update(lesson_params)
        format.turbo_stream { render turbo_stream: turbo_stream.replace( "#{helpers.dom_id(@lesson)}_lesson",partial: "lessons/lesson", locals: {
          lesson: @lesson, join_status: current_user.joined?(@lesson) 
          })}
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(@lesson, partial: "lessons/lesson", locals: {lesson: @lesson})
        end
        format.html { redirect_to lesson_url(@lesson), notice: "Lesson was successfully updated." }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end
  end

  def set_current_user
    Current.user = current_user
  end

  
  def correct_user
    @frind = current_user.lessons.find_by(id: params[:id])
    redirect_to root_path, notice: "Not Authorized To Edit This lesson" if @lesson.nil?
  end

  # DELETE /lessons/1 or /lessons/1.json
  def destroy
    @lesson.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove("#{helpers.dom_id(@lesson)}_lesson")}
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
      format.turbo_stream do
        render turbo_stream: turbo_stream.remove(@lesson, partial: "lessons/lesson", locals: {lesson: @lesson})
      end
      format.html { redirect_to lessons_url, notice: "Lesson was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def join
    @lesson = Lesson.find(params[ :id])
    current_user.join(@lesson)
    respond_to do |format|
      format.turbo_stream do 
        render turbo_stream: private_stream
      end
    end
  end

  def comment
    id =params[:lesson_id]
    @lesson = Lesson.find(params[:lesson_id])
    @lesson.user_id = params[:user_id]
    @lesson.save
    
    @lesson.save
    respond_to do |format|
      format.turbo_stream do 
        render turbo_stream: messageing(id)
      end
    end
  end

  private

  def private_stream
    private_target = "#{helpers.dom_id(@lesson)} private_joins"
    turbo_stream.replace(private_target, 
                          partial: 'joins/private_button',
                          locals:{
                            lesson: @lesson,
                            join_status: current_user.joined?(@lesson)
                        })
  end

  private

  def messageing(id)
    @bmesseages = Bmesseage.all
    turbo_stream.replace("messageing", 
                          partial: 'bmesseages/messages',
                          locals:{
                            bmesseage: @bmesseages,
                            join_status: current_user.joined?(@lesson)
                        })
  end
                 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lesson_params
      params.require(:lesson).permit(:topic, :field, :description, :user_id)
    end

    def bmesseage_params
      params.require(:bmesseage).permit(:body,:user_id)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_button_submit.html.erb
<div class="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
      <!--
        Modal panel, show/hide based on modal state.

        Entering: "ease-out duration-300"
          From: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
          To: "opacity-100 translate-y-0 sm:scale-100"
        Leaving: "ease-in duration-200"
          From: "opacity-100 translate-y-0 sm:scale-100"
          To: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
      -->
      <div class="relative transform overflow-hidden rounded-lg bg-white text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-lg">
        <div class="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
          <div class="sm:flex sm:items-start">
            <div class="mx-auto flex h-12 w-12 flex-shrink-0 items-center justify-center rounded-full bg-red-100 sm:mx-0 sm:h-10 sm:w-10">
              <!-- Heroicon name: outline/exclamation-triangle -->
              <svg class="h-6 w-6 text-red-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 10.5v3.75m-9.303 3.376C1.83 19.126 2.914 21 4.645 21h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 4.88c-.866-1.501-3.032-1.501-3.898 0L2.697 17.626zM12 17.25h.007v.008H12v-.008z" />
              </svg>
            </div>
            <div class="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
              <h3 class="text-lg font-medium leading-6 text-gray-900" id="modal-title">Deactivate account</h3>
              <div class="mt-2">
               
            
              </div>
            </div>
          </div>
        </div>

        <div class="bg-gray-50 px-4 py-3 sm:flex sm:flex-row-reverse sm:px-6">
          <button onclick="closeccc()" type="button" class="inline-flex w-full justify-center rounded-md border border-transparent bg-blue-600 px-4 py-2 text-base font-medium text-white shadow-sm hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 sm:ml-3 sm:w-auto sm:text-sm">Deactivate</button>
          <button onclick="closeccc()"  id="modalClose" type="button" class="mt-3 inline-flex w-full justify-center rounded-md border border-gray-300 bg-white px-4 py-2 text-base font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm">Cancel</button>
        </div>
      </div>
</div>

app/views/lessons/_card_design.html.erb
<div id="<%= dom_id lesson %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Topic:</strong>
    <%= lesson.topic %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Field:</strong>
    <%= lesson.field %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= lesson.description %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this lesson", lesson, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this lesson', edit_lesson_path(lesson),data: {turbo_frame: "model"} , class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium", onclick: "cllee()"  %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/lessons/_form.html.erb
<%= form_with(model: lesson, class: "contents") do |form| %>           
  <div class="p-6 space-y-6">            
  <% if lesson.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
        <% lesson.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-span-6">
    <%= form.label :topic, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300" %>
    <%= form.text_field :topic, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" %>
  </div>

 <div class="col-span-6">
    <%= form.label :field , class: "block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300" %>
    <%= form.text_field :field, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" %>
  </div>

  <div class="col-span-6">
    <%= form.label :description , class: "block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300"%>
    <%= form.text_area :description, rows: 4, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" %>
  </div>
</div>
  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="flex items-center p-6 space-x-2 rounded-b border-t border-gray-200 dark:border-gray-600">
    <%= form.submit class: "inline-flex justify-center rounded-md border border-transparent bg-blue-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 sm:ml-3 focus:ring-offset-2" %>
    <button type="button" onclick="toggleModal('modal-id')"  class="mt-3 inline-flex w-full justify-center rounded-md border border-gray-300 bg-white px-4 py-2 text-base font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm">Cancel</button>
  </div>
  
<% end %>

app/views/lessons/_lesson.html.erb
<div id="<%= dom_id lesson %>">
<li id="<%= "#{dom_id(lesson)}_lesson" %>" class="py-3">
<div class="max-w-2xl mb-3 px-8 py-4 mx-auto bg-white rounded-lg shadow-md dark:bg-gray-800" style="cursor: auto;">
  <div class="flex items-center justify-between">
    <span class="text-sm font-light text-gray-600 dark:text-gray-400"> <%= l lesson.created_at.to_date, format: :short %></span> 
    <div class="flex flex-row ml-20">
        <% if lesson.user == current_user %>
          <%= button_to  lesson_path(lesson), method: :delete,  class: "flex mr-3 space-x-2 items-center px-3 py-2 bg-rose-500 hover:bg-rose-800 rounded-md drop-shadow-md" do %>
            <svg class="fill-white" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="20" height="20"
                viewBox="0 0 24 24">
                <path
                    d="M 10 2 L 9 3 L 3 3 L 3 5 L 21 5 L 21 3 L 15 3 L 14 2 L 10 2 z M 4.3652344 7 L 5.8925781 20.263672 C 6.0245781 21.253672 6.877 22 7.875 22 L 16.123047 22 C 17.121047 22 17.974422 21.254859 18.107422 20.255859 L 19.634766 7 L 4.3652344 7 z">
                </path>
            </svg>
        <% end %>
        <%= link_to  edit_lesson_path(lesson), data: {turbo_frame: "model"} ,class: "flex space-x-2 mr-3 items-center px-3 py-2 bg-green-500 hover:bg-green-800 rounded-md drop-shadow-md", onclick: "toggleModal('modal-id')"  do %>
            <svg class="fill-white" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="20" height="20"
                viewBox="0 0 50 50">
                <path
                    d="M 46.574219 3.425781 C 45.625 2.476563 44.378906 2 43.132813 2 C 41.886719 2 40.640625 2.476563 39.691406 3.425781 C 39.691406 3.425781 39.621094 3.492188 39.53125 3.585938 C 39.523438 3.59375 39.511719 3.597656 39.503906 3.605469 L 4.300781 38.804688 C 4.179688 38.929688 4.089844 39.082031 4.042969 39.253906 L 2.035156 46.742188 C 1.941406 47.085938 2.039063 47.453125 2.292969 47.707031 C 2.484375 47.898438 2.738281 48 3 48 C 3.085938 48 3.171875 47.988281 3.257813 47.964844 L 10.746094 45.957031 C 10.917969 45.910156 11.070313 45.820313 11.195313 45.695313 L 46.394531 10.5 C 46.40625 10.488281 46.410156 10.472656 46.417969 10.460938 C 46.507813 10.371094 46.570313 10.308594 46.570313 10.308594 C 48.476563 8.40625 48.476563 5.324219 46.574219 3.425781 Z M 45.160156 4.839844 C 46.277344 5.957031 46.277344 7.777344 45.160156 8.894531 C 44.828125 9.222656 44.546875 9.507813 44.304688 9.75 L 40.25 5.695313 C 40.710938 5.234375 41.105469 4.839844 41.105469 4.839844 C 41.644531 4.296875 42.367188 4 43.132813 4 C 43.898438 4 44.617188 4.300781 45.160156 4.839844 Z M 5.605469 41.152344 L 8.847656 44.394531 L 4.414063 45.585938 Z">
                </path>
            </svg>
        <%end%>
        <%end%>
         <a class="px-3 py-1 text-sm font-bold text-gray-100 transition-colors duration-200 transform bg-gray-600 rounded cursor-pointer hover:bg-gray-500"><%= lesson.field %></a>
  </div>
  
   
  </div> 
  <div class="mt-2">
    <a href="https://stackdiary.com/" class="text-2xl font-bold text-gray-700 dark:text-white hover:text-gray-600 dark:hover:text-gray-200 hover:underline"><%= lesson.topic %></a> 
    <p class="mt-2 text-gray-600 dark:text-gray-300"><%= lesson.description %></p>
  </div> 
  <div class="flex items-center justify-between mt-4">
   <% if current_user %>
    <%= render 'joins/private_button',lesson: lesson, join_status: join_status %>
   <% else %>
   <%= link_to 'Join  ⟶', new_user_session_path,  class:"text-blue-600 dark:text-blue-400 hover:underline"%>
   <% end %>
    <div class="flex items-center">
      <img src="https://stackdiary.com/140x100.png" alt="Author Photo" class="hidden object-cover w-10 h-10 mx-4 rounded-full sm:block"> 
      <a class="font-bold text-gray-700 cursor-pointer dark:text-gray-200"><%= lesson.user_email %></a>
    </div>
  </div>
</div>
</li>
</div>

app/views/lessons/_lesson_show.html.erb
<div id="<%= dom_id lesson %>">
<div class="max-w-2xl mb-3 px-8 py-4 mx-auto bg-white rounded-lg shadow-md dark:bg-gray-800" style="cursor: auto;">
  <div class="flex items-center justify-between">
    <span class="text-sm font-light text-gray-600 dark:text-gray-400"> <%= l lesson.created_at.to_date, format: :short %></span> 
    <div class="flex flex-row ml-20">
        <% if lesson.user == current_user %>
          <%= button_to  lesson_path(lesson), method: :delete,  class: "flex mr-3 space-x-2 items-center px-3 py-2 bg-rose-500 hover:bg-rose-800 rounded-md drop-shadow-md" do %>
            <svg class="fill-white" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="20" height="20"
                viewBox="0 0 24 24">
                <path
                    d="M 10 2 L 9 3 L 3 3 L 3 5 L 21 5 L 21 3 L 15 3 L 14 2 L 10 2 z M 4.3652344 7 L 5.8925781 20.263672 C 6.0245781 21.253672 6.877 22 7.875 22 L 16.123047 22 C 17.121047 22 17.974422 21.254859 18.107422 20.255859 L 19.634766 7 L 4.3652344 7 z">
                </path>
            </svg>
        <% end %>
        <%= link_to  edit_lesson_path(lesson) ,class: "flex space-x-2 mr-3 items-center px-3 py-2 bg-green-500 hover:bg-green-800 rounded-md drop-shadow-md", onclick: "toggleModal('modal-id')"  do %>
            <svg class="fill-white" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="20" height="20"
                viewBox="0 0 50 50">
                <path
                    d="M 46.574219 3.425781 C 45.625 2.476563 44.378906 2 43.132813 2 C 41.886719 2 40.640625 2.476563 39.691406 3.425781 C 39.691406 3.425781 39.621094 3.492188 39.53125 3.585938 C 39.523438 3.59375 39.511719 3.597656 39.503906 3.605469 L 4.300781 38.804688 C 4.179688 38.929688 4.089844 39.082031 4.042969 39.253906 L 2.035156 46.742188 C 1.941406 47.085938 2.039063 47.453125 2.292969 47.707031 C 2.484375 47.898438 2.738281 48 3 48 C 3.085938 48 3.171875 47.988281 3.257813 47.964844 L 10.746094 45.957031 C 10.917969 45.910156 11.070313 45.820313 11.195313 45.695313 L 46.394531 10.5 C 46.40625 10.488281 46.410156 10.472656 46.417969 10.460938 C 46.507813 10.371094 46.570313 10.308594 46.570313 10.308594 C 48.476563 8.40625 48.476563 5.324219 46.574219 3.425781 Z M 45.160156 4.839844 C 46.277344 5.957031 46.277344 7.777344 45.160156 8.894531 C 44.828125 9.222656 44.546875 9.507813 44.304688 9.75 L 40.25 5.695313 C 40.710938 5.234375 41.105469 4.839844 41.105469 4.839844 C 41.644531 4.296875 42.367188 4 43.132813 4 C 43.898438 4 44.617188 4.300781 45.160156 4.839844 Z M 5.605469 41.152344 L 8.847656 44.394531 L 4.414063 45.585938 Z">
                </path>
            </svg>
        <%end%>
        <%end%>
         <a class="px-3 py-1 text-sm font-bold text-gray-100 transition-colors duration-200 transform bg-gray-600 rounded cursor-pointer hover:bg-gray-500"><%= lesson.field %></a>
  </div>
  
   
  </div> 
  <div class="mt-2">
    <a href="https://stackdiary.com/" class="text-2xl font-bold text-gray-700 dark:text-white hover:text-gray-600 dark:hover:text-gray-200 "><%= lesson.topic %></a> 
    <p class="mt-2 text-gray-600 dark:text-gray-300"><%= lesson.description %></p>
  </div> 
  <div class="flex items-center justify-between mt-4">
  <div class="text-gray-600 dark:text-white " > 
  <%= render 'joins/join_count', lesson: lesson %>
  </div>
    <div class="flex items-center">
      <img src="https://stackdiary.com/140x100.png" alt="Author Photo" class="hidden object-cover w-10 h-10 mx-4 rounded-full sm:block"> 
      <a class="font-bold text-gray-700 cursor-pointer dark:text-gray-200"><%= lesson.user_email %></a>
    </div>
  </div>
</div>
</div>

app/views/lessons/_model.html.erb
<!-- Main modal -->
<div id="modal-id" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 w-full md:inset-0 h-modal md:h-full">

    <div class="relative p-4 w-full max-w-2xl h-full md:h-auto">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
         <%= turbo_frame_tag :model %>
            <!-- Modal header -->
            
            <!-- Modal body form -->
           
            <!-- Modal footer form-->
           
        </div>
    </div>
</div>

<div class="hidden opacity-25 fixed inset-0 z-40 bg-black" id="modal-id-backdrop"></div>

app/views/lessons/edit.html.erb
<%= turbo_frame_tag :model do%>
<div data-controller="turbomodal" data-action="turbo:submit-end->turbomodal#submitEnd">
   <div class="flex justify-between items-start p-4 rounded-t border-b dark:border-gray-600">
                <h3 class="text-xl font-semibold text-gray-900 dark:text-white">
                    Edit Lesson
                </h3>
                <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-toggle="defaultModal" onclick="toggleModal('modal-id')">
                    <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                    <span class="sr-only">Close modal</span>
                </button>
            </div>
    
   <div class="mt-5 md:col-span-2 md:mt-0">
  <%= render "form", lesson: @lesson %>
 </div>
</div>
<%end%>

app/views/lessons/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <div id="test">
  </div>

    <%= turbo_stream_from "public_joins" %>
    <% lessons_channel = current_user ? "private_lessons" : "public_lessons" %>
    <%= turbo_stream_from lessons_channel %>
    <%= turbo_stream_from [@user_gid, 'private_joins'] %>
    <%= content_tag(:div, id: lessons_channel) do %>
      <% @lessons.each do |lesson| %>
      <% if current_user %>
        <%= render  "lessons/lesson",lesson: lesson, join_status: current_user.joined?(lesson), current_user: current_user  %>
      <% else %>
        <%= render "lessons/lesson", lesson: lesson %>
      <% end %>
      <% end %>
    <% end %>
  
</div>

app/views/lessons/new.html.erb
<%= turbo_frame_tag :model do%>
<div data-controller="turbomodal" data-action="turbo:submit-end->turbomodal#submitEnd">

   <div class="flex justify-between items-start p-4 rounded-t border-b dark:border-gray-600">
                <h3 class="text-xl font-semibold text-gray-900 dark:text-white">
                    New Lesson
                </h3>
                <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-toggle="defaultModal" onclick="toggleModal('modal-id')">
                    <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                    <span class="sr-only">Close modal</span>
                </button>
            </div>
    
   <div class="mt-5 md:col-span-2 md:mt-0">
  <%= render "form", lesson: @lesson %>
  </div>
</div>
<%end%>

app/views/lessons/show.html.erb
<div class="mx-auto md:w-3/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
<div class=" flex flex-col justify-center center-item bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700">
    <%= render "lessons/lesson_show", lesson: @lesson %>
    <div class="overflow-y-auto h-72 relative w-full  mx-auto bg-white dark:bg-slate-800 dark:highlight-white/5 shadow-lg ring-1 ring-black/5 rounded-xl flex flex-col divide-y dark:divide-slate-200/5">
    
    <%= turbo_stream_from "messageing" %>
    <%= content_tag(:div, id: "messageing") do %>
    
      <% @bmesseage.each do |bmesseage| %>
        <%= render  "bmesseages/messages", bmesseage: bmesseage, lesson: @lesson %>
      <% end %>
    <% end %>

    </div>
    <%= render 'bmesseages/form', bmesseage: @bmesseages %>
<div>
  </div>
</div>