config/routes.rb
Rails.application.routes.draw do
  resources :bmesseages
  resources :lessons
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  post 'join/:id', to: "lessons#join", as: "join_lesson"

  post 'comment/', to: "lessons#comment", as: "join_comment"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "lessons#index"
end

app/models/bmesseage.rb
class Bmesseage < ApplicationRecord
    belongs_to :user
    belongs_to :lesson

    has_many :messages
    def user_email
        user.email
    end

    after_create_commit :broadcast_new_lesson

    def broadcast_new_lesson
          broadcast_prepend_later_to 'messageing',
                                      target: 'messageing',
                                      partial: 'bmesseages/messages',
                                      locals: { bmesseage: self}
        end

end

app/controllers/bmesseages_controller.rb
class BmesseagesController < ApplicationController
  before_action :set_bmesseage, only: %i[ show edit update destroy ]

  # GET /bmesseages or /bmesseages.json
  def index
    @bmesseages = Bmesseage.all
  end

  # GET /bmesseages/1 or /bmesseages/1.json
  def show
  end

  # GET /bmesseages/new
  def new
    @bmesseage = Bmesseage.new
  end

  # GET /bmesseages/1/edit
  def edit
  end

  # POST /bmesseages or /bmesseages.json
  def create
    @bmesseage = Bmesseage.new(bmesseage_params)

    respond_to do |format|
      if @bmesseage.savelesson
        format.turbo_stream { render turbo_stream: turbo_stream.prepend( "messageing" , partial: "bmesseages/messages", locals: {
          bmesseage: @bmesseage 
          })}
        format.html { redirect_to bmesseage_url(@bmesseage), notice: "Bmesseage was successfully created." }
        format.json { render :show, status: :created, location: @bmesseage }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bmesseage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bmesseages/1 or /bmesseages/1.json
  def update
    respond_to do |format|
      if @bmesseage.update(bmesseage_params)
        format.html { redirect_to bmesseage_url(@bmesseage), notice: "Bmesseage was successfully updated." }
        format.json { render :show, status: :ok, location: @bmesseage }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bmesseage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bmesseages/1 or /bmesseages/1.json
  def destroy
    @bmesseage.destroy

    respond_to do |format|
      format.html { redirect_to bmesseages_url, notice: "Bmesseage was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bmesseage
      @bmesseage = Bmesseage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bmesseage_params
      params.require(:bmesseage).permit(:body)
    end
end

app/helpers/bmesseages_helper.rb
module BmesseagesHelper
end

app/views/bmesseages/_bmesseage.html.erb
<div id="<%= dom_id bmesseage %>">

<div class="flex items-center justify-center w-screen h-screen bg-white dark:bg-gray-800">
<div class="bg-white dark:bg-gray-800 text-black dark:text-gray-200 p-4 antialiased flex max-w-lg">
  <img class="rounded-full h-8 w-8 mr-2 mt-1 " src="https://picsum.photos/id/1027/200/200"/>
  <div>
    <div class="bg-gray-100 dark:bg-gray-700 rounded-3xl px-4 pt-2 pb-2.5">
      <div class="font-semibold text-sm leading-relaxed"><%= bmesseage.user_email %></div>
      <div class="text-normal leading-snug md:leading-normal"
      >  <%= bmesseage.body %> </div>
    </div>
    <div class="text-sm ml-4 mt-0.5 text-gray-500 dark:text-gray-400"><%= time_ago_in_words(bmesseage.created_at) %></div>
    <div class="bg-white dark:bg-gray-700 border border-white dark:border-gray-700 rounded-full float-right -mt-8 mr-0.5 flex shadow items-center ">
      <svg class="p-0.5 h-5 w-5 rounded-full z-20 bg-white dark:bg-gray-700" xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' viewBox='0 0 16 16'><defs><linearGradient id='a1' x1='50%' x2='50%' y1='0%' y2='100%'><stop offset='0%' stop-color='#18AFFF'/><stop offset='100%' stop-color='#0062DF'/></linearGradient><filter id='c1' width='118.8%' height='118.8%' x='-9.4%' y='-9.4%' filterUnits='objectBoundingBox'><feGaussianBlur in='SourceAlpha' result='shadowBlurInner1' stdDeviation='1'/><feOffset dy='-1' in='shadowBlurInner1' result='shadowOffsetInner1'/><feComposite in='shadowOffsetInner1' in2='SourceAlpha' k2='-1' k3='1' operator='arithmetic' result='shadowInnerInner1'/><feColorMatrix in='shadowInnerInner1' values='0 0 0 0 0 0 0 0 0 0.299356041 0 0 0 0 0.681187726 0 0 0 0.3495684 0'/></filter><path id='b1' d='M8 0a8 8 0 00-8 8 8 8 0 1016 0 8 8 0 00-8-8z'/></defs><g fill='none'><use fill='url(#a1)' xlink:href='#b1'/><use fill='black' filter='url(#c1)' xlink:href='#b1'/><path fill='white' d='M12.162 7.338c.176.123.338.245.338.674 0 .43-.229.604-.474.725a.73.73 0 01.089.546c-.077.344-.392.611-.672.69.121.194.159.385.015.62-.185.295-.346.407-1.058.407H7.5c-.988 0-1.5-.546-1.5-1V7.665c0-1.23 1.467-2.275 1.467-3.13L7.361 3.47c-.005-.065.008-.224.058-.27.08-.079.301-.2.635-.2.218 0 .363.041.534.123.581.277.732.978.732 1.542 0 .271-.414 1.083-.47 1.364 0 0 .867-.192 1.879-.199 1.061-.006 1.749.19 1.749.842 0 .261-.219.523-.316.666zM3.6 7h.8a.6.6 0 01.6.6v3.8a.6.6 0 01-.6.6h-.8a.6.6 0 01-.6-.6V7.6a.6.6 0 01.6-.6z'/></g></svg>
      <svg class="p-0.5 h-5 w-5 rounded-full -ml-1.5 bg-white dark:bg-gray-700" xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' viewBox='0 0 16 16'><defs><linearGradient id='a2' x1='50%' x2='50%' y1='0%' y2='100%'><stop offset='0%' stop-color='#FF6680'/><stop offset='100%' stop-color='#E61739'/></linearGradient><filter id='c2' width='118.8%' height='118.8%' x='-9.4%' y='-9.4%' filterUnits='objectBoundingBox'><feGaussianBlur in='SourceAlpha' result='shadowBlurInner1' stdDeviation='1'/><feOffset dy='-1' in='shadowBlurInner1' result='shadowOffsetInner1'/><feComposite in='shadowOffsetInner1' in2='SourceAlpha' k2='-1' k3='1' operator='arithmetic' result='shadowInnerInner1'/><feColorMatrix in='shadowInnerInner1' values='0 0 0 0 0.710144928 0 0 0 0 0 0 0 0 0 0.117780134 0 0 0 0.349786932 0'/></filter><path id='b2' d='M8 0a8 8 0 100 16A8 8 0 008 0z'/></defs><g fill='none'><use fill='url(#a2)' xlink:href='#b2'/><use fill='black' filter='url(#c2)' xlink:href='#b2'/><path fill='white' d='M10.473 4C8.275 4 8 5.824 8 5.824S7.726 4 5.528 4c-2.114 0-2.73 2.222-2.472 3.41C3.736 10.55 8 12.75 8 12.75s4.265-2.2 4.945-5.34c.257-1.188-.36-3.41-2.472-3.41'/></g></svg>
      <span class="text-sm ml-1 pr-1.5 text-gray-500 dark:text-gray-300">3</span>
    </div>
  </div>
</div>
</div>
</div>

app/views/bmesseages/_form.html.erb
<%= turbo_frame_tag :message do%>
<%= form_with(model: bmesseage, url: join_comment_path, class: "contents") do |form| %>
<div class="p-6 max-w-sm bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700">

  <div class="col-span-6">
    <%= form.label :body , class: "block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300"%>
    <%= form.text_area :body, rows: 4, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" %>
  </div>
  <%= form.hidden_field :lesson_id, value: @lesson.id %>

  <div class="flex items-center p-6 space-x-2 rounded-b border-t border-gray-200 dark:border-gray-600">
    <%= form.submit "Send" , class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
  </div>
<% end %>
<%end%>

app/views/bmesseages/_messages.html.erb
<div id="<%= dom_id bmesseage %>">

<div class="flex items-center justify-center w-screen h-screen bg-white dark:bg-gray-800">
<div class="bg-white dark:bg-gray-800 text-black dark:text-gray-200 p-4 antialiased flex max-w-lg">
  <img class="rounded-full h-8 w-8 mr-2 mt-1 " src="https://picsum.photos/id/1027/200/200"/>
  <div>
    <div class="bg-gray-100 dark:bg-gray-700 rounded-3xl px-4 pt-2 pb-2.5">
      <div class="font-semibold text-sm leading-relaxed"><%= bmesseage.user_email %></div>
      <div class="text-normal leading-snug md:leading-normal"
      >  <%= bmesseage.body %> </div>
    </div>
    <div class="text-sm ml-4 mt-0.5 text-gray-500 dark:text-gray-400"><%= time_ago_in_words(bmesseage.created_at) %></div>
    <div class="bg-white dark:bg-gray-700 border border-white dark:border-gray-700 rounded-full float-right -mt-8 mr-0.5 flex shadow items-center ">
      <svg class="p-0.5 h-5 w-5 rounded-full z-20 bg-white dark:bg-gray-700" xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' viewBox='0 0 16 16'><defs><linearGradient id='a1' x1='50%' x2='50%' y1='0%' y2='100%'><stop offset='0%' stop-color='#18AFFF'/><stop offset='100%' stop-color='#0062DF'/></linearGradient><filter id='c1' width='118.8%' height='118.8%' x='-9.4%' y='-9.4%' filterUnits='objectBoundingBox'><feGaussianBlur in='SourceAlpha' result='shadowBlurInner1' stdDeviation='1'/><feOffset dy='-1' in='shadowBlurInner1' result='shadowOffsetInner1'/><feComposite in='shadowOffsetInner1' in2='SourceAlpha' k2='-1' k3='1' operator='arithmetic' result='shadowInnerInner1'/><feColorMatrix in='shadowInnerInner1' values='0 0 0 0 0 0 0 0 0 0.299356041 0 0 0 0 0.681187726 0 0 0 0.3495684 0'/></filter><path id='b1' d='M8 0a8 8 0 00-8 8 8 8 0 1016 0 8 8 0 00-8-8z'/></defs><g fill='none'><use fill='url(#a1)' xlink:href='#b1'/><use fill='black' filter='url(#c1)' xlink:href='#b1'/><path fill='white' d='M12.162 7.338c.176.123.338.245.338.674 0 .43-.229.604-.474.725a.73.73 0 01.089.546c-.077.344-.392.611-.672.69.121.194.159.385.015.62-.185.295-.346.407-1.058.407H7.5c-.988 0-1.5-.546-1.5-1V7.665c0-1.23 1.467-2.275 1.467-3.13L7.361 3.47c-.005-.065.008-.224.058-.27.08-.079.301-.2.635-.2.218 0 .363.041.534.123.581.277.732.978.732 1.542 0 .271-.414 1.083-.47 1.364 0 0 .867-.192 1.879-.199 1.061-.006 1.749.19 1.749.842 0 .261-.219.523-.316.666zM3.6 7h.8a.6.6 0 01.6.6v3.8a.6.6 0 01-.6.6h-.8a.6.6 0 01-.6-.6V7.6a.6.6 0 01.6-.6z'/></g></svg>
      <svg class="p-0.5 h-5 w-5 rounded-full -ml-1.5 bg-white dark:bg-gray-700" xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' viewBox='0 0 16 16'><defs><linearGradient id='a2' x1='50%' x2='50%' y1='0%' y2='100%'><stop offset='0%' stop-color='#FF6680'/><stop offset='100%' stop-color='#E61739'/></linearGradient><filter id='c2' width='118.8%' height='118.8%' x='-9.4%' y='-9.4%' filterUnits='objectBoundingBox'><feGaussianBlur in='SourceAlpha' result='shadowBlurInner1' stdDeviation='1'/><feOffset dy='-1' in='shadowBlurInner1' result='shadowOffsetInner1'/><feComposite in='shadowOffsetInner1' in2='SourceAlpha' k2='-1' k3='1' operator='arithmetic' result='shadowInnerInner1'/><feColorMatrix in='shadowInnerInner1' values='0 0 0 0 0.710144928 0 0 0 0 0 0 0 0 0 0.117780134 0 0 0 0.349786932 0'/></filter><path id='b2' d='M8 0a8 8 0 100 16A8 8 0 008 0z'/></defs><g fill='none'><use fill='url(#a2)' xlink:href='#b2'/><use fill='black' filter='url(#c2)' xlink:href='#b2'/><path fill='white' d='M10.473 4C8.275 4 8 5.824 8 5.824S7.726 4 5.528 4c-2.114 0-2.73 2.222-2.472 3.41C3.736 10.55 8 12.75 8 12.75s4.265-2.2 4.945-5.34c.257-1.188-.36-3.41-2.472-3.41'/></g></svg>
      <span class="text-sm ml-1 pr-1.5 text-gray-500 dark:text-gray-300">3</span>
    </div>
  </div>
</div>
</div>
</div>

app/views/bmesseages/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing bmesseage</h1>

  <%= render "form", bmesseage: @bmesseage %>

  <%= link_to "Show this bmesseage", @bmesseage, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to bmesseages", bmesseages_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/bmesseages/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Bmesseages</h1>
    <%= link_to 'New bmesseage', new_bmesseage_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="bmesseages" class="min-w-full">
    <%= render @bmesseages %>
  </div>
</div>

app/views/bmesseages/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New bmesseage</h1>

  <%= render "form", bmesseage: @bmesseage %>

  <%= link_to 'Back to bmesseages', bmesseages_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/bmesseages/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @bmesseage %>

    <%= link_to 'Edit this bmesseage', edit_bmesseage_path(@bmesseage), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this bmesseage', bmesseage_path(@bmesseage), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to bmesseages', bmesseages_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>